version: "3.7"
services:
  elasticmq-native:
    container_name: elasticmq-container
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
      - type: bind
        source: ./custom.conf
        target: /opt/elasticmq.conf
    image: softwaremill/elasticmq-native
