PREFIX cat: <http://cat.nationalarchives.gov.uk/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>

SELECT  ?recordDescriptionUri ?label ?identifier
WHERE
{ ?recordDescriptionUri prov:specializationOf  ?recordConceptUri ;
                        dct:subject ?subject .
  ?subject dct:description ?label ;
           dct:subject ?identifier .
}