PREFIX cat: <http://cat.nationalarchives.gov.uk/>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?recordDescriptionUri ?accessRights
WHERE { ?recordDescriptionUri prov:specializationOf ?recordConceptUri ;
                              dct:accessRights ?accessRightsBNode .
        ?accessRightsBNode rdf:type dct:RightsStatement ;
                           odrl:hasPolicy ?accessRights .
      }
