name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test (JDK ${{ matrix.jdk }} / ${{ matrix.os }})
    env:
      GITHUB_TOKEN: ${{ github.token }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        jdk: [8, 11]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Check Scala format
        run: sbt scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
      - name: Run unit tests
        run: sbt test
      - uses: isbang/compose-action@v1.5.1
        name: Start docker compose
        with:
          compose-file: "./docker-compose.yml"
      - name: Run integration tests
        run: sbt -v IntegrationTest/test

  package:
    name: Create Software Packages
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Build Zip Package
        run: sbt universal:packageBin
      - name: Build TGZ Package
        run: sbt universal:packageZipTarball
      - name: Build RPM package
        run: sbt rpm:packageBin
