name: Validate Async API spec

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Validate Async API spec
    env:
      GITHUB_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run Spectral
        uses: stoplightio/spectral-action@latest
        with:
          file_glob: './schema/omega-services.async.api.yaml'
          spectral_ruleset: './schema/validate-omega-services.spectral.yaml'
